interface AvisItem {
  id: number;
  date: string;
  avis: string;
  note: number;
}

export const avis: AvisItem[] = [
  {
    id: 0,
    date: "2024-05-04",
    avis: "Merci pour votre aide précieuse ! Les étapes étaient bien expliquées et le processus très transparent.",
    note: 5,
  },
  {
    id: 1,
    date: "2024-01-23",
    avis: "Ravi de la simplicité du service. J'ai pu me concentrer sur mon activité sans me soucier des papiers administratifs.",
    note: 5,
  },
  {
    id: 2,
    date: "2024-04-09",
    avis: "Excellente plateforme, très intuitive. Le support client a répondu rapidement à mes questions. Hautement recommandé !",
    note: 5,
  },
  {
    id: 3,
    date: "2023-11-03",
    avis: "Je n'aurais jamais pensé que créer une auto-entreprise serait si facile ! Merci à Info Autoentreprise pour leur efficacité.",
    note: 5,
  },
  {
    id: 4,
    date: "2024-03-03",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 5,
  },
  {
    id: 5,
    date: "2023-12-15",
    avis: "Le site est bien structuré, et j'ai pu créer mon auto-entreprise en quelques clics. Les explications étaient très claires.",
    note: 4,
  },
  {
    id: 6,
    date: "2024-04-07",
    avis: "Info Autoentreprise est top ! Le site m'a guidé à travers chaque étape. Je suis très satisfait de mon expérience.",
    note: 4,
  },
  {
    id: 7,
    date: "2023-11-08",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 5,
  },
  {
    id: 8,
    date: "2024-01-27",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 4,
  },
  {
    id: 9,
    date: "2024-04-25",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 4,
  },
  {
    id: 10,
    date: "2024-03-29",
    avis: "Info Autoentreprise a rendu le processus de démarrage de mon entreprise très fluide. Merci pour l'assistance détaillée !",
    note: 5,
  },
  {
    id: 11,
    date: "2023-12-07",
    avis: "Le site est bien structuré, et j'ai pu créer mon auto-entreprise en quelques clics. Les explications étaient très claires.",
    note: 4,
  },
  {
    id: 12,
    date: "2024-02-10",
    avis: "Excellente plateforme, très intuitive. Le support client a répondu rapidement à mes questions. Hautement recommandé !",
    note: 5,
  },
  {
    id: 13,
    date: "2024-02-11",
    avis: "Excellente plateforme, très intuitive. Le support client a répondu rapidement à mes questions. Hautement recommandé !",
    note: 4,
  },
  {
    id: 14,
    date: "2023-11-02",
    avis: "Excellente plateforme, très intuitive. Le support client a répondu rapidement à mes questions. Hautement recommandé !",
    note: 5,
  },
  {
    id: 15,
    date: "2023-11-19",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 4,
  },
  {
    id: 16,
    date: "2023-11-25",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 4,
  },
  {
    id: 17,
    date: "2024-02-23",
    avis: "Je n'aurais jamais pensé que créer une auto-entreprise serait si facile ! Merci à Info Autoentreprise pour leur efficacité.",
    note: 4,
  },
  {
    id: 18,
    date: "2024-02-25",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 5,
  },
  {
    id: 19,
    date: "2024-01-14",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 4,
  },
  {
    id: 20,
    date: "2024-04-01",
    avis: "Info Autoentreprise est top ! Le site m'a guidé à travers chaque étape. Je suis très satisfait de mon expérience.",
    note: 5,
  },
  {
    id: 21,
    date: "2024-03-11",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 5,
  },
  {
    id: 22,
    date: "2024-02-20",
    avis: "Info Autoentreprise est top ! Le site m'a guidé à travers chaque étape. Je suis très satisfait de mon expérience.",
    note: 5,
  },
  {
    id: 23,
    date: "2023-12-05",
    avis: "Ravi de la simplicité du service. J'ai pu me concentrer sur mon activité sans me soucier des papiers administratifs.",
    note: 4,
  },
  {
    id: 24,
    date: "2024-04-06",
    avis: "Info Autoentreprise a rendu le processus de démarrage de mon entreprise très fluide. Merci pour l'assistance détaillée !",
    note: 5,
  },
  {
    id: 25,
    date: "2024-04-12",
    avis: "Info Autoentreprise a rendu le processus de démarrage de mon entreprise très fluide. Merci pour l'assistance détaillée !",
    note: 5,
  },
  {
    id: 26,
    date: "2024-01-22",
    avis: "Merci pour votre aide précieuse ! Les étapes étaient bien expliquées et le processus très transparent.",
    note: 4,
  },
  {
    id: 27,
    date: "2023-11-29",
    avis: "Ravi de la simplicité du service. J'ai pu me concentrer sur mon activité sans me soucier des papiers administratifs.",
    note: 5,
  },
  {
    id: 28,
    date: "2023-12-25",
    avis: "Le site est bien structuré, et j'ai pu créer mon auto-entreprise en quelques clics. Les explications étaient très claires.",
    note: 4,
  },
  {
    id: 29,
    date: "2023-11-11",
    avis: "Info Autoentreprise est top ! Le site m'a guidé à travers chaque étape. Je suis très satisfait de mon expérience.",
    note: 4,
  },
  {
    id: 30,
    date: "2023-10-15",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 5,
  },
  {
    id: 31,
    date: "2023-12-01",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 5,
  },
  {
    id: 32,
    date: "2024-03-20",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 4,
  },
  {
    id: 33,
    date: "2024-01-10",
    avis: "Excellente plateforme, très intuitive. Le support client a répondu rapidement à mes questions. Hautement recommandé !",
    note: 5,
  },
  {
    id: 34,
    date: "2024-03-01",
    avis: "Je n'aurais jamais pensé que créer une auto-entreprise serait si facile ! Merci à Info Autoentreprise pour leur efficacité.",
    note: 4,
  },
  {
    id: 35,
    date: "2024-02-28",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 5,
  },
  {
    id: 36,
    date: "2024-03-10",
    avis: "Le site est bien structuré, et j'ai pu créer mon auto-entreprise en quelques clics. Les explications étaient très claires.",
    note: 4,
  },
  {
    id: 37,
    date: "2024-04-17",
    avis: "Le site est bien structuré, et j'ai pu créer mon auto-entreprise en quelques clics. Les explications étaient très claires.",
    note: 5,
  },
  {
    id: 38,
    date: "2024-04-10",
    avis: "Merci pour votre aide précieuse ! Les étapes étaient bien expliquées et le processus très transparent.",
    note: 5,
  },
  {
    id: 39,
    date: "2024-01-17",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 5,
  },
  {
    id: 40,
    date: "2023-11-29",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 4,
  },
  {
    id: 41,
    date: "2024-02-18",
    avis: "Ravi de la simplicité du service. J'ai pu me concentrer sur mon activité sans me soucier des papiers administratifs.",
    note: 4,
  },
  {
    id: 42,
    date: "2023-11-27",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 4,
  },
  {
    id: 43,
    date: "2024-04-02",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 4,
  },
  {
    id: 44,
    date: "2024-03-07",
    avis: "Ravi de la simplicité du service. J'ai pu me concentrer sur mon activité sans me soucier des papiers administratifs.",
    note: 5,
  },
  {
    id: 45,
    date: "2023-12-30",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 5,
  },
  {
    id: 46,
    date: "2024-01-08",
    avis: "Service impeccable. Les démarches étaient bien moins compliquées que je ne le pensais grâce à Info Autoentreprise.",
    note: 4,
  },
  {
    id: 47,
    date: "2024-03-18",
    avis: "J'ai trouvé la création de mon auto-entreprise incroyablement simple grâce à Info Autoentreprise. Tout était clair et rapide !",
    note: 4,
  },
  {
    id: 48,
    date: "2024-01-24",
    avis: "Je n'aurais jamais pensé que créer une auto-entreprise serait si facile ! Merci à Info Autoentreprise pour leur efficacité.",
    note: 5,
  },
  {
    id: 49,
    date: "2023-12-06",
    avis: "Je n'aurais jamais pensé que créer une auto-entreprise serait si facile ! Merci à Info Autoentreprise pour leur efficacité.",
    note: 4,
  },
  {
    id: 50,
    date: "2024-01-23",
    avis: "Une expérience vraiment positive avec Info Autoentreprise. Tout a été géré en ligne sans tracas. C'est un gain de temps précieux.",
    note: 4,
  },
  {
    id: 51,
    date: "2024-01-26",
    avis: "Le site est bien structuré, et j'ai pu créer mon auto-entreprise en quelques clics. Les explications étaient très claires.",
    note: 4,
  },
];
